name: Secrets Scanning

on:
  push:
    branches: [ 'main', '**' ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  SERVICE_NAME: "codeql"

jobs:
  talisman_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          path: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - name: Install talisman and add to PATH
        run: |
          sh install-talisman.sh
          echo "$GITHUB_WORKSPACE/codeql" >> $GITHUB_PATH
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - name: Talisman Verify
        run: talisman-verify-repo.sh
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}