name: Secrets Scanning

on:
  push:
    branches: [ "*" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  SERVICE_NAME: "codeql"

jobs:
  talisman_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          path: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
#      - name: Checkout cicd resources
#        uses: actions/checkout@v2
#        with:
#          repository: otto-ec/aquanar_starter
#          path: ${{ github.workspace }}/aquanar_starter
#          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install talisman and add to PATH
        run: |
          sh install-talisman.sh
          echo "$GITHUB_WORKSPACE/aquanar_starter" >> $GITHUB_PATH
        working-directory:${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - name: Talisman Verify
        run: $GITHUB_WORKSPACE/aquanar_starter/bin/talisman-verify-repo.sh
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}/